update psr/http-message requirement to allow v1 or v2
plank/laravel-mediable pull request #329
Opened 2023-09-07 01:01 UTC by jason-nabooki

https://github.com/plank/laravel-mediable/pull/318 bumped the requirement to a hard v2 which is causing issues with other packages that require v1.

Could it be considered to allow the proposed `^1.0|^2.0` was there any hard requirement for `v2` or just a housekeeping change?

2023-09-07 01:02 UTC, jason-nabooki commented
cc @frasmage

2023-09-12 00:34 UTC, frasmage approved these changes

2023-09-12 00:38 UTC, frasmage commented
actually, there are hard requirements for only using one version. The `\Plank\Mediable\Stream` class in the library implements the `\Psr\Http\Message\StreamInterface` from that package. The methods signatures changed between v1 and v2 and the implementing class can only adhere to one of them

2023-09-12 00:39 UTC, frasmage requested changes
Stream handling implementation will break if using v1

2023-09-13 09:17 UTC, jason-nabooki commented
Ah, the types added to the `Stream.php` methods in https://github.com/plank/laravel-mediable/pull/318 require `v2`? I couldn't see much else in https://github.com/plank/laravel-mediable/compare/5.9.0...5.9.1

So I guess the options are to revert or leave it as is. If you'd be open to reverting, I could submit a PR.

The issue we're facing is the official Laravel `vapor-core` package strictly requires `v1` (recently introduced).

2024-03-28 02:28 UTC, frasmage commented
in the `v6` branch, I've replaced this package's Stream class with the `guzzlehttp/psr7` implementation, which appears to support  both versions of the `psr\http-message` specification

2024-03-28 02:28 UTC, closed without merging